/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.service.Service;

/**
 *
 * @author sakulambo
 */
public class Add_Food extends JFrame {

    /**
     * Creates new form Add_Food2
     */
    public Add_Food() {
        super("Añadir comida");
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jlFoodComment = new javax.swing.JLabel();
        jcbPartOfMenu = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaFoodComment = new javax.swing.JTextArea();
        jcbFoodType = new javax.swing.JComboBox<>();
        jlFoodId = new javax.swing.JLabel();
        jlFoodName = new javax.swing.JLabel();
        jlFoodPrice = new javax.swing.JLabel();
        jtfFoodId = new javax.swing.JTextField();
        jlPartOfMenu = new javax.swing.JLabel();
        jtfFoodName = new javax.swing.JTextField();
        jlFoodTyoe = new javax.swing.JLabel();
        jtfFoodPrice = new javax.swing.JTextField();
        jlImageLabel = new javax.swing.JLabel();
        jlFoodImage = new javax.swing.JLabel();
        jbSearchImage = new javax.swing.JButton();
        jbAccept = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jbDeleteImage = new javax.swing.JButton();
        genericPane = new JOptionPane();
        service = new Service();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jlFoodComment.setText("Comentarios");

        jcbPartOfMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Entrante", "Primero", "Segundo", "Postre"}));

        jtaFoodComment.setColumns(20);
        jtaFoodComment.setRows(5);
        jtaFoodComment.setMinimumSize(new java.awt.Dimension(4, 32));
        jScrollPane1.setViewportView(jtaFoodComment);

        jcbFoodType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Entrante", "Carne", "Pescado", "Verdura", "Pasta", "Postre"}));

        jlFoodId.setText("IDProducto");

        jlFoodName.setText("Nombre");

        jlFoodPrice.setText("Precio");

        jtfFoodId.setEditable(false);

        jlPartOfMenu.setText("Parte del menu");

        jlFoodTyoe.setText("Grupo alimenticio");

        jlImageLabel.setText("Imagen");

        jbSearchImage.setText("Buscar...");
        jbSearchImage.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                chooser = new JFileChooser();
                chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
                //filter the files
                FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg", "gif", "png");
                chooser.addChoosableFileFilter(filter);
                int result = chooser.showSaveDialog(Add_Food.this);
                //if the user click on save in Jfilechooser
                if (result == JFileChooser.APPROVE_OPTION) {
                    File selectedFile = chooser.getSelectedFile();
                    String path = selectedFile.getAbsolutePath();
                    jlFoodImage.setIcon(ResizeImage(path));
                } //if the user click on save in Jfilechooser
                else if (result == JFileChooser.CANCEL_OPTION) {
                    System.out.println("No File Select");
                }
            }

        });

        jbAccept.setText("Aceptar");
        jbAccept.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAcceptMouseClicked(evt);
            }
        });

        jbCancel.setText("Cancelar");
        jbCancel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setDefaultCloseOperation(HIDE_ON_CLOSE);
            }
        });

        jbDeleteImage.setText("Eliminar");
        jbDeleteImage.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jlFoodImage.setIcon(null);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jlFoodId)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jtfFoodId, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGap(9, 9, 9)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(jlFoodName)
                                                                                                .addComponent(jlFoodPrice))
                                                                                        .addGap(18, 18, 18)
                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                                .addComponent(jtfFoodName, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                                                                                .addComponent(jtfFoodPrice)))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(jbSearchImage)
                                                                                        .addGap(18, 18, 18)
                                                                                        .addComponent(jbDeleteImage)))))
                                                        .addComponent(jlFoodImage, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jlFoodTyoe)
                                                                        .addComponent(jcbFoodType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jlPartOfMenu)
                                                                        .addComponent(jcbPartOfMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jlFoodComment)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(156, 156, 156)
                                                                .addComponent(jbAccept)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jbCancel))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addComponent(jlImageLabel)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(4, 4, 4)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jlFoodId)
                                                                        .addComponent(jtfFoodId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jlFoodName)
                                                                        .addComponent(jtfFoodName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(11, 11, 11)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jlFoodPrice)
                                                                        .addComponent(jtfFoodPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jlFoodComment)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                                .addComponent(jlImageLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jlFoodTyoe)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jcbFoodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jlPartOfMenu)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jcbPartOfMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(43, 43, 43)))
                                .addComponent(jlFoodImage, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbSearchImage)
                                        .addComponent(jbAccept)
                                        .addComponent(jbCancel)
                                        .addComponent(jbDeleteImage))
                                .addGap(35, 35, 35))
        );
        pack();
    }

    private void jbAcceptMouseClicked(java.awt.event.MouseEvent evt) {
        boolean request = jtfFoodName.getText().isEmpty() || jtfFoodPrice.getText().isEmpty();
        try {
//            saveImage();
//            uploadImage();

            if (!request) {              
               
                
            } else {
                JOptionPane.showMessageDialog(genericPane, "Campos Vacíos!\n"
                        + "Por favor, rellene los siguientes campos:\n"
                        + "- Nombre\n"
                        + "- Precio", "CAMPOS VACIOS", JOptionPane.ERROR_MESSAGE);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(jlFoodImage.getWidth(), jlFoodImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    public void saveImage() throws IOException {
        File file = new File("src/model/images/" + jtfFoodId.getText());
        ImageIcon imageI = (ImageIcon) jlFoodImage.getIcon();
        Image image = imageI.getImage();
        BufferedImage img = new BufferedImage(image.getWidth(null), image.getWidth(null), BufferedImage.TYPE_INT_RGB);
        try {
            if (!file.exists()) {
                file.createNewFile();
            }
            if (!file.canRead()) {
                file.setReadable(true);
                file.setExecutable(true);
                file.setWritable(true);
            }
            ImageIO.write(img, "bmp", file);

        } catch (FileNotFoundException e) {
        }

    }

   /* public void uploadImage() throws IOException {
        String server = "127.0.0.1";
        int port = 21;
        String user = "ANONYMOUS_LOGON";
        String pass = "admin";

        FTPClient ftpClient = new FTPClient();
        try {

            ftpClient.connect(server, port);
            ftpClient.login(user, pass);
            ftpClient.enterLocalPassiveMode();

            ftpClient.setFileType(FTP.BINARY_FILE_TYPE);

            // APPROACH #1: uploads first file using an InputStream
            File firstLocalFile = new File("src/model/images" + jtfFoodId.getText());

            String firstRemoteFile = jtfFoodId.getText();
            boolean done;
            try (InputStream inputStream = new FileInputStream(firstLocalFile)) {
                System.out.println("Start uploading first file");
                done = ftpClient.storeFile(firstRemoteFile, inputStream);
            }
            if (done) {
                System.out.println("The first file is uploaded successfully.");
            }
        } catch (IOException ex) {
            System.out.println("Error: " + ex.getMessage());
            ex.printStackTrace();
        } finally {
            if (ftpClient.isConnected()) {
                ftpClient.logout();
                ftpClient.disconnect();
            }
        }

    }*/

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> jcbFoodType;
    private javax.swing.JComboBox<String> jcbPartOfMenu;
    private javax.swing.JLabel jlFoodId;
    private javax.swing.JLabel jlFoodName;
    private javax.swing.JLabel jlFoodPrice;
    private javax.swing.JLabel jlPartOfMenu;
    private javax.swing.JLabel jlFoodTyoe;
    private javax.swing.JLabel jlFoodComment;
    private javax.swing.JLabel jlImageLabel;
    private javax.swing.JLabel jlFoodImage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaFoodComment;
    private javax.swing.JTextField jtfFoodId;
    private javax.swing.JTextField jtfFoodName;
    private javax.swing.JTextField jtfFoodPrice;
    private javax.swing.JButton jbAccept;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbSearchImage;
    private javax.swing.JButton jbDeleteImage;
    private javax.swing.JFileChooser chooser;
    private javax.swing.JOptionPane genericPane;
    private Service service;
    // End of variables declaration   

}
